language: go

go:
  - 1.8.x
  - 1.9.x
  - 1.10.x

script:
  - go test -v github.com/Hunsin/bee/mart
  - go test -v github.com/Hunsin/bee/mart/carrefour
  - go test -v github.com/Hunsin/bee/mart/rt
  - go test -v github.com/Hunsin/bee/mart/wellcome